name: Feature request
description: Suggest an improvement or new capability
title: "feat: "
labels:
  - enhancement
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What problem are you trying to solve?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: What would you like to happen?
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: What other approaches did you consider?
    validations:
      required: false
  - type: textarea
    id: contract-impact
    attributes:
      label: Contract impact
      description: Does this affect commands/schemas/config/errors? If yes, describe.
    validations:
      required: false
